apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-index-html-configmap"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! I got deployed in {{ .Values.env.name }} Environment using Helm Chart </h1>
    </html