apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-index-html-configmap"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
data:
  index.html:
  {{- if .Values.nginx.serverHtml }}
    {{- toYaml .Values.nginx.serverHtml | indent 1 }}
  {{- end }}