apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: "{{ .Release.Name }}-deployment"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-chart.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      {{- if .Values.nginx.initContainers }}
        {{ toYaml .Values.nginx.initContainers | nindent 8 }}
      {{- end }}
      containers:
      {{- if .Values.nginx.containers }}
        {{ toYaml .Values.nginx.containers | nindent 8 }}
      {{- end }}
