apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nginx-chart.selectorLabels" . | nindent 4 }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}